In [3]:
import numpy as np

In [4]:
# Create an array of 10 zeros
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [5]:
# Create an array of 10 ones
np.ones(10)

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [6]:
# Create an array of 10 fives
arr = np.ones(10)
arr + 4 

array([ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.])

In [7]:
# Create an array of the integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [8]:
# Create an array of all the even integers from 10 to 50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [9]:
# Create a 3x3 matrix with values ranging from 0 to 8
arr = np.arange(0,9)
arr
arr_one = arr.reshape(3,3)
arr_one

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# Create a 3x3 identity matrix

In [13]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [14]:
# Use NumPy to generate a random number between 0 and 1

In [21]:
np.random.rand()

0.28981959513138167