In [1]:
# Numpy 
# Numpy is a Linear Algebra Library for Python, the reason it is so important for Data Science wiht Python is that almost
# all libraries in the PyData Ecosystem rely on Numpy as on of their main buildings blocks
# Numpy is also incredibly fast, as it has buildings to C libraries
# NumPy arrays are the main way we will use Numpy throughout the course 
# Numpy arrats essentially come in two flavors: vectors and matrices.
# Vectors are strictly 1-d arrays and matrices are 2-d (but you shout note a matrix can still have only one row or one
# colum )

In [3]:
my_list = [1,2,3]

In [4]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.zeros((4,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [12]:
np.ones((5,6))

array([[ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.]])

In [14]:
np.linspace(0,5,10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [15]:
# identety metrix
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [18]:
np.random.rand()

0.9363594444550987

In [20]:
np.random.rand(5,5)

array([[ 0.91233485,  0.08876199,  0.74740702,  0.25241837,  0.24745413],
       [ 0.14849345,  0.26462659,  0.88604198,  0.68710749,  0.67571369],
       [ 0.75083949,  0.74480712,  0.29745207,  0.72382305,  0.79834132],
       [ 0.51055711,  0.71321396,  0.71046698,  0.71204547,  0.42483107],
       [ 0.29160574,  0.50988074,  0.77970302,  0.10608138,  0.08605117]])

In [22]:
np.random.randn(3)

array([ 0.76161947,  0.1542242 , -0.84717065])

In [23]:
np.random.randint(4)

0

In [24]:
np.random.randint(4)

3

In [26]:
np.random.randint(0,20,4)

array([18, 14, 14, 19])

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
ranarr = np.random.randint(0,50,10)

In [30]:
ranarr

array([12, 18, 14, 49, 40,  4, 23, 36,  1,  4])

In [31]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
ranarr.max()

49

In [33]:
ranarr.min()

1

In [34]:
ranarr.argmax()

3

In [35]:
arr.shape

(25,)

In [36]:
arr_one = arr.reshape(5,5)

In [37]:
arr_one.shape

(5, 5)

In [41]:
arr.dtype

dtype('int64')

In [ ]:
# indexing & selection