In [1]:
# Numpy 
# Numpy is a Linear Algebra Library for Python, the reason it is so important for Data Science wiht Python is that almost
# all libraries in the PyData Ecosystem rely on Numpy as on of their main buildings blocks
# Numpy is also incredibly fast, as it has buildings to C libraries
# NumPy arrays are the main way we will use Numpy throughout the course 
# Numpy arrats essentially come in two flavors: vectors and matrices.
# Vectors are strictly 1-d arrays and matrices are 2-d (but you shout note a matrix can still have only one row or one
# colum )

In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1, 2, 3],[4, 5, 6],[7, 8, 9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
np.zeros((2,2))

NameError: name 'np' is not defined