In [3]:
# Numpy

In [5]:
[[12,14,124],[],[]]

[[12, 14, 124], [], []]

In [6]:
import numpy

In [8]:
n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [10]:
type(n) # n dimenzional array

numpy.ndarray

In [11]:
n.reshape(3,9) # 2 dimenzional array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [12]:
n.reshape(3,3,3) # 3 dimenzional array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [13]:
import cv2

In [16]:
image = cv2.imread("smallgray.png",0)

In [18]:
image 

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [19]:
cv2.imwrite('newimg.png', image)

True