# NumPy

In [1]:
import numpy as np

## NumPy Arrays

In [2]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [3]:
my_long_array = [[1,2,3], [4,5,6],[7,8,9]]
np.array(my_long_array)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones(4)

array([1., 1., 1., 1.])

In [10]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [14]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(3)

array([0.65286941, 0.75364377, 0.33909695])

In [16]:
np.random.rand(3,2)

array([[0.49189584, 0.02046453],
       [0.71912592, 0.97701235],
       [0.71833813, 0.81786392]])

In [18]:
np.random.randn(4,2)

array([[ 0.05914092, -0.06638857],
       [-1.91494916,  2.36062001],
       [ 2.83576826,  1.92371306],
       [ 0.67462332, -0.49747248]])

In [23]:
np.random.randint(1,20,4)

array([17,  3, 15,  1])

In [25]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
arr.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [28]:
arr.dtype

dtype('int64')